name: taxi_tuc
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  socket_io_client: ^2.0.3+1
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  shared_preferences: ^2.3.2
  google_maps_flutter: ^2.13.1
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  google_sign_in: ^6.2.1
  http: ^1.5.0
  geolocator: ^10.1.0
  geocoding: ^2.1.0
  smooth_page_indicator: ^1.1.0
  flutter_polyline_points: ^2.0.0
  uuid: ^4.4.0
  font_awesome_flutter: ^10.10.0
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_native_splash: ^2.4.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - .env
    - assets/images/pin_origen.png
    - assets/images/pin_destino.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"
  min_sdk_android: 21 # o tu versión mínima

flutter_native_splash:
  # Colores de fondo
  #color: "#FFFFFF"           # claro
  #color_dark: "#000000"      # oscuro

  # Imagen principal
  image: assets/images/splash_inicio.png
  image_dark: assets/images/splash_inicio.png

    # Android 12 (recomendado definir imágenes con padding)
  android_12:
    image: assets/images/splash_inicio.png
    image_dark: assets/images/splash_inicio.png
    icon_background_color: "#FFFFFF"
    icon_background_color_dark: "#000000"

  # Plataformas
  android: true
  ios: true
  web: false

  # Layout / modo de ajuste
  fullscreen: true
  android_gravity: center        # top, center, bottom, etc.
  ios_content_mode: center 
